apiVersion: v1
kind: Service
metadata:
  name: react-gke-service
  namespace: react-gke
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: react-gke
  type: NodePort
